### ISSUE TITLE
python print() causes excess new line

### ISSUE THREAD

**Issue by srakitnican** [yevmel/squid-rpm-cache#3]
Like the title says is the "\n" really necessary?

In my case it was spilling errors in log: `2016/08/26 21:38:32 kid1| helperHandleRead: unexpected reply on channel 0 from store_id #Hlpr1 ''`

I have tested function print() in both python2 and python3. In both versions print() itself outputs new line.

Thanks for sharing the scripts, btw!

**Comment by yevmel** [comment]
fixed the script, thx for the feedback.
